server:
  port: 8077
spring:
  cloud:
    gateway:
      routes:
        - id: userInsuranceServiceRoute
          predicates:
            - Path=/policycatalogue/**
          uri: "lb://user-insurance-service"
          filter:
            - AuthenticationFilter
        - id: insuranceCartServiceRoute
          predicates:
            - Path=/insurancecart/**
          uri: "lb://insurance-cart-service"
          filter:
            - AuthenticationFilter
        - id: feedbackServiceRoute
          predicates:
            - Path=/feedback/**
          uri: "lb://feedback-service"
          filter:
            - AuthenticationFilter
        - id: discountServiceRoute
          predicates:
            - Path=/discount/**
          uri: "lb://discount-service"
          filter:
            - AuthenticationFilter
        - id: userAuthenticationServiceRoute
          predicates:
            - Path=/authenticate/**
          uri: "lb://user-authentication-service"
  application:
    name: App-GATEWAY
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:7777/eureka/"
