server:
  port: 8077
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: productServiceRoute
          predicates:
            - Path=/products/**
          uri:  lb://product-service
          
        - id: cartServiceRoute
          predicates:
            - Path=/shoppingcart/**
          uri:  lb://cart-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
