server:
  port: 8077
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: userAuthenticationServiceRoute
          predicates:
            - Path=/authenticate/**
          uri: lb://user-authentication-service

        - id: userInsuranceServiceRoute
          predicates:
            - Path=/policycatalogue/**
          uri: lb://user-insurance-service

        - id: insuranceCartServiceRoute
          predicates:
            - Path=/insurancecart/**
          uri: lb://insurance-cart-service

        - id: feedbackServiceRoute
          predicates:
            - Path=/feedback/**
          uri: lb://feedback-service

        - id: discountServiceRoute
          predicates:
            - Path=/discount/**
          uri: lb://discount-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
